### PR TITLE
New demos: Prompts, Chains & Memory, Agents/Tools, Embedding Documents

### PR DESCRIPTION
**Pull request by eldermoraes**
@lordofthejars, can you check if this is a good path to follow for Quarkus IV?

### CODE REVIEW

**Comment by eldermoraes** [comment]
Thank you for your comments, @kdubois !

About the extensions part, is this valid only for CLI commands or also for the Maven ones?

**Comment by kdubois** [comment]
should be valid for both!

**Comment by eldermoraes** [comment]
Just updated this PR with the new demos. Would love to hear feedbacks about it.

**Comment by kdubois** [comment]
@eldermoraes I reviewed the first prompt page and added a few tiny fixes. Somehow I was allowed to push it straight to your fork, hope you don't mind lol

**Comment by eldermoraes** [comment]
Not at all, @kdubois ! Thank you.

**Pull request merged**
