### PR TITLE
Added a missing comma to the 'quarkus:add-extension' command

### PR DESCRIPTION
**Pull request by eldermoraes**
A small fix that was breaking the "Spring Compatibility" section in the tutorial.

### CODE REVIEW

**Comment by eldermoraes** [comment]
Also found and fixed a missing "@Inject".

**Comment by eldermoraes** [comment]
Really? I was presenting to a customer and got alerted by the IDE about the missing "@Inject". So I just added it right away and then committed to the repo.

Would you prefer to remove it?

**Comment by kdubois** [comment]
No I think it's better if it's there.  The official documentation shows it as well so it was the right thing to do :D . https://quarkus.io/guides/rest-client

**Comment by eldermoraes** [comment]
👍

**Comment by lordofthejars** [comment]
It's not necessary o use Inject; I never use it. IDE probably has its own parser

**Pull request merged**
