### PR TITLE
Proofread the tutorial

### PR DESCRIPTION
**Pull request by gsmet**
I went through all the content and made the following changes:
- fixed typos
- reported some issues that were not that easy to fix (for instance the use of dead punkapi.com in some sections)
- adjusted the first tutorials to use Jackson instead of JSON-B: we recommend using Jackson. Also it avoids having to go back to switch from JSON-B to Jackson when dealing with Spring
- the reactive sections are still using JSON-B for two reasons: they are using some JSON-P features and I couldn't test things given the API is not available. When reworking them, we should switch them to Jackson too.

This is a bit massive, I will go through the changes and add comments when they are needed.

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
@kdubois Probably a good idea to add whitespace when reviewing. Small cog above the diff / Hide whitespace / Apply.

/cc @geoand @cescoffier

**Comment by gsmet** [comment]
@kdubois once you agree on the changes, let me do a pass to check that I didn't break the formatting (unclosed backticks for instance).
I will do it locally but let's agree on the changes first so that I don't do it twice.

**Comment by kdubois** [comment]
Looks great, thanks for going through and fixing / improving the content!   I like the switch to Jackson as well.

**Comment by gsmet** [comment]
@kdubois OK, I went through the content again, and went through the all the steps I changed (so until REST Client).

Things work but I had some bad surprises with dev mode when adding the extensions. Once, dev mode somehow didn't reload the model properly and I ended up with some classes (the MicroProfile REST Client ones) being missing.

Even using `s` didn't fix it.

It worked after a full restart of the dev mode.

I'll try to reproduce this but it doesn't seem fully reproducible and is not related to my changes so I would say all these changes are good to go.

**Comment by gsmet** [comment]
@kdubois I added a small step to make sure people wait for Quarkus to be reloaded after having added an extension. Once PostgreSQL is installed, you have the Dev Service starting and it's relatively slow.

I think that might explain what I saw (but we should try to see how we could fix it to survive the issue)

**Comment by kdubois** [comment]
LGTM!

**Pull request merged**
